### PR TITLE
fix: Remote API and no internet connection

### LINKED ISSUE #979: Smapp does not connect to Remote API in case there was a connection error
### Environment
* Smapp version: 0.2.6 | develop

### Describe the bug
In case if wallet file was set up to use the remote API and there was no internet connection on the startup of Smapp — it asks to choose the network, but it can't fetch the discovery service. Then if the internet connection recovered and User clicks on refresh and chooses the network — Smapp updates the wallet file, but it does not connects to the selected API.

### Steps to reproduce
1. Open Smapp and switch to remote API
2. Close Smapp, turn the internet off
3. Open Smapp and unlock the wallet
4. Wait for the network selection screen and "No networks available" in the dropdown
5. Turn on the internet
6. Click "Refresh" and choose the network and remote API

It also does not work if you choose the network and API from the Network screen, while the network was not selected, aka if you click on the "Skip" button on the 4th step.

### Expected behavior
Smapp should show the wallet screen, and it should be connected to the remote API.
So if you go to the Network screen — there should be information about the selected remote API and the network (layers, etc).

### Actual behavior
It does not connect to the remote API.
If you open the Network screen it will tell that "No network selected" and propose to choose one.
If you click on the button and choose the same one — nothing changes.

### PR DESCRIPTION
**Pull request by maparr**
it closes #979

### CODE REVIEW

**Comment by monikasmolarek** [comment]
I checked as I got the review request, but I suppose it's not yet finalized? 

https://user-images.githubusercontent.com/89876259/224145347-c1d84e24-5051-499b-92a9-96f6cec7fb43.mov

**Comment by maparr** [comment]
Hi @monikasmolarek , 
based on the steps to reproduce
```
Open Smapp and unlock the wallet
Wait for the network selection screen and "No networks available" in the dropdown
Turn on the internet
```

we should stay on the same screen. I got your point and added a title about NO INTERNET CONNECTION for the dropdown message. Refresh working right now automatically.

https://user-images.githubusercontent.com/54288612/224220510-4c270e0c-7e2a-4c6a-9a48-79547d675238.mov

**Comment by monikasmolarek** [comment]
No no, my point is that the issue is still there, it's not fixed. 
no matter how I try or when I turn on the Internet. 
Below the rec following exactly the steps described in the bug report (build including your latest commit)

https://user-images.githubusercontent.com/89876259/224424085-6ba3a1db-8dff-4651-b207-47c43c5f9a7d.mov

**Comment by maparr** [comment]
Hi @monikasmolarek , seems finally resolved. Remote api + wallet / node working. Can u check and share your thoughts .

**Review by monikasmolarek — APPROVED** [review]
seems to be working as expected

**Review by brusherru — APPROVED** [review]
👍

**Pull request merged**
