### PR TITLE
Fix forgetting smeshing is enabled

### PR DESCRIPTION
**Pull request by IlyaVi**

### CODE REVIEW

**Comment by IlyaVi** [comment]
bug description: set up smeshing, wait until node is synced, close the app and then reopen it. Go to smeshing tab and app will state that smeshing is not set

**Comment by yaelmhoffman** [comment]
This issue is not fixed.

**Comment by avive** [comment]
@yaelmhoffman - plz describe the steps to reproduce and what build you were testing and on what platform e.g. 0.0.6.RC2 on win 10 home....

**Comment by avive** [comment]
And I think you want to comment that the issue is still happening in the comment of the issue itself and not this PR which was merged...

**Comment by yaelmhoffman** [comment]
Using build 0.0.6.RC2 on Windows 10 Home.

Closed app. Reopened app. It says that smeshing needs to be set up, even though I've already set up smeshing upon installation. 
smeshing_not_set_up_on_restart

**Comment by yaelmhoffman** [comment]
Build: v0.0.6RC5
OS: Windows 10 home
Fix confirmed!

**Pull request merged**
