### PR TITLE
Show atxs count

### PR DESCRIPTION
**Pull request by brusherru**
### It includes:
- Refactored how API is integrated and generated: now API is a submodule, and it is possible to use `v1` and `v2alpha1` at the same time
- Display amount of synced ATXs on the Network screen, when it is syncing activations:
   <video src="https://github.com/spacemeshos/smapp/assets/1897530/288ce3b7-98f3-4438-a7ef-c20ca43cc5f9">Your browser does not support video tag</video>

### Prerequisite:
It is based on https://github.com/spacemeshos/smapp/pull/1684

### How to test:
Build go-spacemesh from develop and put it into `node/{mac|windows|linux}` and then run Smapp `yarn && yarn start`

### CODE REVIEW

**Review by pigmej — COMMENTED** [review]
Can't we show "per epoch' ? The cumulative number looks "weird" but maybe it's my personal feeling.

**Comment by brusherru** [comment]
> The cumulative number looks "weird" but maybe it's my personal feeling.

E.g. `Syncing activations for epoch 12 (32123)...`? 🤔

**Comment by pigmej** [comment]
> > The cumulative number looks "weird" but maybe it's my personal feeling.
> 
> E.g. `Syncing activations for epoch 12 (32123)...`? 🤔

Something like that :) not 100% but looks easier to track imo and makes the user to see the epochs etc.

**Comment by brusherru** [comment]
It depends on https://github.com/spacemeshos/go-spacemesh/pull/5645 (build go-sm from this branch for tests)

**Review by monikasmolarek — COMMENTED** [review]
I tried to build locally the go-sm from the PR you mentioned, as well as the develop branch (when pr was already merged) but even though smapp starts, the node underneath doesn’t want to start (on both Mac and Win). I don’t have the logs to attach cause the node never started. I tried to run the same go-sm build without smapp and it runs normally. In general I had no problem building smapp earlier with locally built go-sm while testing other PRs even earlier this week. 

Just as a reminder, go-sm v1.4.0-alpha.1 which was experimental and is quite old now had some issues with database and the node didn’t want to run. But the 15alpha3-nomain was fine. 

Is there anything I could or should do to debug it?

**Review by pigmej — APPROVED** [review]

**Review by pigmej — DISMISSED** [review]

**Pull request merged**
