### PR TITLE
Use `setWindowOpenHandler()` in favor of deprecated `new-window` event

### PR DESCRIPTION
**Pull request by cl8n**
noticed a warning for this one in stderr. the event is removed in electron 22

### CODE REVIEW

**Comment by maparr** [comment]
Hi @cl8n , thank you for the contribution!
I will check this soon.

**Comment by maparr** [comment]
Hi @cl8n , we didn't use electron 22 for now, may u describe where did u face this warning?

**Comment by Stizerg** [comment]
When clicking  a purple button in smapp  that opens a Browser window.
Screenshot:
https://discord.com/channels/623195163510046732/691262184050786305/1129022709628665896

**Review by brusherru — APPROVED** [review]

**Comment by brusherru** [comment]
@cl8n thanks for the contribution! ❤️

**Comment by cl8n** [comment]
woops sorry for not responding there, thanks for the screenshot. that was indeed where I noticed the warning :ok_hand:

**Pull request merged**
