### PR TITLE
Release CI: sign windows installer & fix release workflow

### LINKED ISSUE #162: Sign windows installer
Using Spacemesh EV code signing cert

### LINKED ISSUE #751: Update release artifacts listing in releases
- Change label `Mac` to `macOS`.
- Order mac after Windows release at the top and above linux distros. Rational is order by OS popularity with home users.

I do these manually for recent release and this should be updated in automation.

### PR DESCRIPTION
**Pull request by brusherru**
It closes #162 and closes #751

Please, check out the automatically created draft (also it contains links to artifacts): https://github.com/spacemeshos/smapp/releases/tag/untagged-6fc496a0120f26073f39

And few questions (please answer by numbers):
1. Right now this workflow is triggered by any tag. Should this workflow be triggered only by `v*.*.*` (release) and `v*.*.*-*` (pre-release) tags?
2. What program name we should provide? (the more detailed question was here: https://github.com/spacemeshos/smapp/issues/162#issuecomment-893833373)
3. To bundle a release I download the latest **release** of `go-spacemesh` (not pre-release). Is it correct?
4. In continuation, for PR builds I use any latest release (pre-release or release). And it makes us possible to test new features using bleeding-edge builds of Node. So builds for PR and release builds may work differently, and this is a problem. However, I have an idea of how to manage it:

### Release flow
1. Create `release-*` branch
2. Commit changelog / version bump / something else
3. Open a PR with the name "Release vX.X.X".
3. It runs `PR-build` GHA workflow with one difference (if branch name starts with `release-`): it downloads the latest release (not pre-release) of `go-spacemesh`
4. When the bot posts a comment with links to artifacts (unsigned yet), we should test it.
5. When we made sure that there are no errors, push the tag.
6. It triggers the building and signing process (release workflow).
7. When we got a release draft, we can test it again (if we want) and publish the release.

Do you agree with it?
If so, I need up to a couple of hours more, to implement it.

### CODE REVIEW

**Comment by avive** [comment]
> 1. Right now this workflow is triggered by any tag. Should this workflow be triggered only by `v*.*.*` (release) and `v*.*.*-*` (pre-release) tags?

I think it is good to trigger it with v prefix in the tag.

> 2. What program name we should provide? (the more detailed question was here: [Sign windows installer #162 (comment)](https://github.com/spacemeshos/smapp/issues/162#issuecomment-893833373))

`Spacemesh App`

> 3. To bundle a release I download the latest **release** of `go-spacemesh` (not pre-release). Is it correct?
I think that what we want is to be able to bundle any go-spacemesh release by tag and not just assume latest. It will give us more flexibility.

> 4. In continuation, for PR builds I use any latest release (pre-release or release). And it makes us possible to test new features using bleeding-edge builds of Node. So builds for PR and release builds may work differently, and this is a problem. However, I have an idea of how to manage it:

I think we should always config a smapp release to work with a specific version of go-sm github release and never assume latest. I think you want to have a go-sm release string param in GHA and use that. If we want to change PRs to work with a different node release then we can just change this param in the GHA script.

> ### Release flow
> 1. Create `release-*` branch
> 2. Commit changelog / version bump / something else
> 3. Open a PR with the name "Release vX.X.X".
> 4. It runs `PR-build` GHA workflow with one difference (if branch name starts with `release-`): it downloads the latest release (not pre-release) of `go-spacemesh`
> 5. When the bot posts a comment with links to artifacts (unsigned yet), we should test it.
> 6. When we made sure that there are no errors, push the tag.
> 7. It triggers the building and signing process (release workflow).
> 8. When we got a release draft, we can test it again (if we want) and publish the release.
> 
> Do you agree with it?
> If so, I need up to a couple of hours more, to implement it.

Yes with the change to always use a specific go-sm release from a string param in GHA. e.g. `v0.1.24`.

**Comment by brusherru** [comment]
> I think we should always config a smapp release to work with a specific version of go-sm github release and never assume latest. I think you want to have a go-sm release string param in GHA and use that.

So in this case there is no need to make special rules for releases, like `release-*` branch name, because it will work the same for all of PRs. But I'll create a page in Wiki when we'll finish with this PR, called "Release process".

To achieve the same and fixed version of `go-spacemesh`, I created a `/node/use-version` file which contains a string with a version like a tag in GitHub releases. E.G. `v0.1.45` is the current latest one. And both of workflows will look on this file to fetch the needed version of Node. Also, this file will be used to cache `go-spacemesh`.
Also, I've added `yarn verify:node-version` script, which has already been integrated into `yarn start` and `yarn build` scripts, which checks that the specified version matches with the version of Node. And then it can show three types of messages: OK (matches), WARNING (does not match, but `NODE_ENV=development`), ERROR (does not match, production). In the latest case, it will exit with error code 1. So it will fail CI workflow and pay attention to this error.

**Comment by brusherru** [comment]
image
🙌

**Comment by brusherru** [comment]
Everything is done.
Here is a link to the release draft: https://github.com/spacemeshos/smapp/releases/tag/untagged-23c177f2843fb7ce58e9
Before the merge, I'll remove the tag and delete this draft.

P.S.
I hope we got a lot of space on GCS and it doesn't cost much. :)

**Comment by avive** [comment]
Regarding the releases, it will be great if this minor issue can be fixed: https://github.com/spacemeshos/smapp/issues/751

**Comment by avive** [comment]
I think it will be good if you can provide short summary in repo's readme regarding how release artifacts for dev builds  and production builds work.

**Comment by avive** [comment]
> I hope we got a lot of space on GCS and it doesn't cost much. :)

Can't we just periodically cleanup old builds from that share?

**Review by IlyaVi — DISMISSED** [review]

**Comment by brusherru** [comment]
> Can't we just periodically cleanup old builds from that share?

We can do it automatically without special jobs in CI. GCS has a built-in feature "rules". So we can create a separate bucket for temporary artifacts (like PR builds) and set the deletion rule.
I just need another bucket secret to upload PR builds in this bucket and this thing will be done :)
Release builds use a tag name, so if we had to re-push the same tag a few times — artifacts should be overwritten.

**Comment by brusherru** [comment]
@avive I've done with #751 and also updated README.md
Please, take a look at the two last commits (related to README.md) and if everything is fine, please approve PR.
Then I'll merge it.

**Review by avive — APPROVED** [review]
LGTM

**Pull request merged**
