### PR TITLE
fix: set up local node TCP/UDP port

### LINKED ISSUE #1051: Set up Local node TCP and UDP port number
### Environment

- Smapp version: 0.2.10 | prerelease
- Node version: v0.2.19-beta.0
- OS: Windows 10 Home + macOS Ventura Version 13.0.1

### Describe the bug

Setting up Local node TCP and UDP port number does not work:  `sudo lsof -PiTCP -sTCP:LISTEN` did not show the change even though the new port is saved (displayed) in the settings after Smapp restart. Even after system restart. Same for Win and Mac.

### Steps to reproduce

1. I open the Smapp settings and go to the "Advanced" section, "Local node TCP and UDP port number" option.
2. I put a new port number in the input field and click the "Set Port" button.
3. I restart Smapp.
4. I check the Port number saved in the settings.
5. I check my system ports, i.e. for Mac: `sudo lsof -PiTCP -sTCP:LISTEN`

### Expected behavior

The TCP port number should be effectively changed after submitting the change and restarting Smapp.

### Actual behavior

The new port is only seven in the settings in Smapp, did not affect the actual system ports settings. 

Dec-18-2022 23-47-15

Dec-18-2022 23-49-13

### Logs

app-log:

```
[2022-12-18 23:45:57.606] [error] NodeService, in grpc StatusStream, error: {"code":13,"details":"Received RST_STREAM with code 2 triggered by internal client error: read ECONNRESET","metadata":{"internalRepr":{},"options":{}}} 
[2022-12-18 23:45:57.607] [error] NodeService, in grpc ErrorStream, error: {"code":13,"details":"Received RST_STREAM with code 2 triggered by internal client error: read ECONNRESET","metadata":{"internalRepr":{},"options":{}}} 
[2022-12-18 23:45:57.608] [error] TransactionService, in grpc TransactionService.TransactionsStateStream, error: {"code":13,"details":"Received RST_STREAM with code 2 triggered by internal client error: read ECONNRESET","metadata":{"internalRepr":{},"options":{}}} ; args: "Retries left: 5"
[2022-12-18 23:45:57.609] [info]  NodeService, in grpc StatusStream ended, output: null 
[2022-12-18 23:45:57.609] [info]  NodeService, in grpc StatusStream shutted down, output: null 
[2022-12-18 23:45:57.610] [info]  NodeService, in grpc ErrorStream ended, output: null 
[2022-12-18 23:45:57.610] [info]  NodeService, in grpc ErrorStream shutted down, output: null 
[2022-12-18 23:46:07.536] [info]  Checking for update
[2022-12-18 23:46:07.568] [debug] update-error NetError: Error: net::ERR_NAME_NOT_RESOLVED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:101:7169)
    at SimpleURLLoaderWrapper.emit (node:events:527:28)
    at SimpleURLLoaderWrapper.emit (node:domain:475:12)
[2022-12-18 23:46:10.508] [error] SmesherService, in grpc call SmesherService.PostConfig, error: {"code":14,"details":"No connection established","metadata":{"internalRepr":{},"options":{}}} 
[2022-12-18 23:46:10.509] [error] SmesherService, in grpc call SmesherService.SmesherID, error: {"code":14,"details":"No connection established","metadata":{"internalRepr":{},"options":{}}} 
[2022-12-18 23:46:10.509] [error] SmesherService, in grpc call SmesherService.PostSetupStatus, error: {"code":14,"details":"No connection established","metadata":{"internalRepr":{},"options":{}}} 
[2022-12-18 23:46:10.511] [info]  NodeManager, in startNode, output: "spawning node" ; args: ["/Applications/Spacemesh.app/Contents/node/go-spacemesh","--config","/Users/monikasmolarek/Library/Application Support/Spacemesh/node-config.json","-d","/Users/monikasmolarek/Library/Application Support/Spacemesh/node-data/1e0acdbd"]
[2022-12-18 23:46:10.526] [error] NodeService, in grpc call NodeService.Echo, error: {"code":14,"details":"No connection established","metadata":{"internalRepr":{},"options":{}}} 
[2022-12-18 23:46:10.528] [error] SmesherService, in grpc call SmesherService.PostSetupComputeProviders, error: {"code":14,"details":"No connection established","metadata":{"internalRepr":{},"options":{}}} 
[2022-12-18 23:46:11.002] [error] NodeService, in grpc call NodeService.Status, error: {"code":14,"details":"No connection established","metadata":{"internalRepr":{},"options":{}}} 
[2022-12-18 23:46:11.028] [error] NodeService, in grpc call NodeService.Echo, error: {"code":14,"details":"No connection established","metadata":{"internalRepr":{},"options":{}}} 
[2022-12-18 23:46:11.508] [error] NodeService, in grpc call NodeService.Status, error: {"code":14,"details":"No connection established","metadata":{"internalRepr":{},"options":{}}} 

```

### How to fix 

tbu

### PR DESCRIPTION
**Pull request by maparr**
It closes #1051 

Settings section with the port number removed.

Example. 

will be available at 127.0.0.1:PORT
```
DISCOVERY_URL=http://127.0.0.1:8000/networks.json GRPC_PUBLIC_PORT=9099 yarn start 
DISCOVERY_URL=http://127.0.0.1:8000/networks.json GRPC_PRIVATE_PORT=9094 yarn start
```

### CODE REVIEW

**Review by monikasmolarek — DISMISSED** [review]
note: Tested only on macOs, I needed to switch to the latest release on Win

**Comment by maparr** [comment]
need to be updated after https://github.com/spacemeshos/smapp/pull/1213

**Comment by maparr** [comment]
have a restriction right now to run the node on the different port number

**Comment by monikasmolarek** [comment]
It works with a custom build, but we do not recommend building and running SMAPP locally (inter alia because of the autoupdates).
However, I cannot run the build (from the last github comment) with these flags. My mistake here, or should those flags be added to the code?

Screenshot 2023-05-16 at 18 42 06
[spacemesh-log-0774eaf6.txt](https://github.com/spacemeshos/smapp/files/11490140/spacemesh-log-0774eaf6.txt)

**Review by monikasmolarek — APPROVED** [review]

**Comment by maparr** [comment]
additionally, we can do it through the config file 
example
```
  "api": {
    "grpc-public-services": ["debug", "global", "mesh", "node", "transaction", "activation"],
    "grpc-public-listener": "0.0.0.0:9092",
    "grpc-private-services": ["smesher"],
    "grpc-private-listener": "0.0.0.0:9093",
    "grpc-json-listener": "0.0.0.0:9094"
  },
  ```

**Review by brusherru — APPROVED** [review]

**Pull request merged**
