### PR TITLE
Fix a bunch of small UI bugs

### LINKED ISSUE #772: Content overflow display area in Transaction Log screen
1. Set app window to min size.
2. Click `all transaction` in wallet screen.

Result: content overflows the display area:
overflow

Expected: resize content area background so content doesn't overflow.

### PR DESCRIPTION
**Pull request by brusherru**
It fixes #772, #773, #793, #779, #791.
Each issue is fixed within a separate commit.
Please, check it out commit by commit.

### CODE REVIEW

**Comment by avive** [comment]
Don't you want to check that builds pass before UI fixes review?

**Comment by brusherru** [comment]
Sorry. I'll ask for a review after all checks passed next time.

**Comment by avive** [comment]
> Sorry. I'll ask for a review after all checks passed next time.

It's okay - I'll review the UI stuff as soon you tell me it is ready.

**Comment by brusherru** [comment]
@avive it is ready ;)

**Comment by avive** [comment]
I think it is time to bump smapp versions to 0.2.x from 0.1.x...

**Comment by avive** [comment]
Installed on macOS after deleting [app_support]/Spacemesh.
Getting this. Please fix text of dialog box not pickling up text color from dark theme - it should be white and not black when dark theme is on....

Screen Shot 2021-08-19 at 2 51 50 PM

**Comment by brusherru** [comment]
Fixed within a new commit

**Comment by avive** [comment]
Confirmed that all UI issues are resolved.

**Review by avive — APPROVED** [review]

**Pull request merged**
