### PR TITLE
A second bunch of small fixes (pre 0.2)

### LINKED ISSUE #829: Wrong sync status percentage display in network screen
### Environment

* Smapp version: 0.2.0 beta0

### Describe the bug
Sync % seems to not being rounded down causing 100% to be displayed when sync is close to finish.

### Steps to reproduce
1. Sync a local managed node.
2. Observe sync % display in network screen.

### Expected behavior
% should be 99% while syncing and only reach 100% when sync is done.

### Actual behavior
Display is 100% x-n/x when sync almost reaches 100%.

Screen Shot 2021-12-04 at 10 40 25 AM

### PR DESCRIPTION
**Pull request by brusherru**
It fixes #829, #830, #831, #832 and also fixes a couple of small things without issues.

### CODE REVIEW

**Comment by avive** [comment]
Some minor tx related display issues:
## Send TX screen
- [x] summary on right: To address should be in format 0x12AF...1234 - like in all other places we show an address. Current display is: `0x5...6068`.
- [x] `Amount` should be all-caps like other summary area fields, e.g. `AMOUNT`.

## Summary Screen (after clicking send)
- [x] To address is in this format `0x59...6068` - should be `0x59AF...606B`.

## SMH SENT! confirmation screen
- [x] Tx id format is `0x71...9904`. Use `0x7134...9904`.

## TX Log - details view
- [x] From and to fields address is in wrong format. e.g. should be `0x1234...1234` and not `0x12...1234`.
- [ ] Fee amount is 0 (should be the fee user selected to pay in smidge.
- [x] Tx id format is `0x71...9904`. Use `0x7134...9904`.

**Comment by avive** [comment]
new transaction error - try entering this in the to address: `0x12...1234` (and enter a valid amount) - result - you can continue and execute the tx but you'll get an error when trying to create the xdr. We must validate that the to address is a valid address, e.g. 0x[20_hex_chars] or if we want to be more robust also support [20_hex_chars] - everything else should be an input validation error. User shouldn't be able to go `next` when the to address is not a valid address.

**Comment by brusherru** [comment]
@avive done with all stuff you have listed.

Additionally tweaked amount input. Previously, if you set 1 SMH and click "next" and then back, you'll see "1000000000000 SMH" (but since you're not touching this input it doesn't affect anything). Now it checks the amount and shows it as an SMH or Smidge and converts in it.

**Comment by avive** [comment]
I verified all fixes besides the FEE issue that we need to resolve.

**Review by avive — APPROVED** [review]

**Pull request merged**
