### PR TITLE
feat(): add index for mnemonic words

### LINKED ISSUE #1249: [Copy Words] - 12 words backup - add index numbers
### Rationale

Since we now have 12 words backup as an obligatory step in the wallet creation process - it would it be great to tweak the “copy words” option.
We currently copy only the array of words, which is annoying - we have to count them to know their order/sequence number to finalize the setup. Can we also have their index number copied to the clipboard?
Screenshot 2023-05-10 at 20 55 46

### Prerequisites
/
### User story

- [ ] I open Smapp and click SETUP
- [ ] I create a new Wallet and get to the 12 words backup step
- [ ] I click "Copy Words"
- [ ] I get the list of words with their order number copied to the clipboard
- [ ] I don't have to put additional effort in counting/figuring out the word's sequence number to complete the next step - confirming the mnemonics 

### Acceptance criteria

Provide some steps that an end-user would be able to perform when the feature could be considered as implemented. E.g.:

- [ ] The basic scenario works as described
- [ ] The numbers and words are correctly copied 

### Out of scope
/

### PR DESCRIPTION
**Pull request by maparr**
it closes #1249 
Screenshot 2023-06-05 at 17 58 15

### CODE REVIEW

**Review by monikasmolarek — DISMISSED** [review]

**Review by brusherru — CHANGES_REQUESTED** [review]
Since we're making another output format, then we should support parsing such format in the `WordsRestore` component as well (both formats).

**Comment by maparr** [comment]
working on it

**Comment by maparr** [comment]
on video copy paste from prev standard and new one, both works

https://github.com/spacemeshos/smapp/assets/54288612/025a8682-1142-4d7f-8ff7-1695a9262505


Screenshot 2023-06-06 at 11 43 38
Screenshot 2023-06-06 at 11 43 34

**Review by brusherru — APPROVED** [review]
👍

**Pull request merged**
