### PR TITLE
Provide types for GRPC Services

### PR DESCRIPTION
**Pull request by brusherru**
There is no issue.
It is related to https://github.com/spacemeshos/smapp/issues/799#p3, proposal №2.
These changes help to write and maintain code related to communication with Node.
And I'm using these changes within my current task: #766 

Probably, I will add one more commit about passing types through IPC pub/sub.

I propose to merge it after the changes of @IlyaVi.
Please, review it carefully, since I have no idea how to test it comprehensively. 😬 

---
There are two commits.
1. [Generate types for GRPC](https://github.com/spacemeshos/smapp/pull/809/commits/5990275dc0c2d4dc83cd8cf6a6e921739acdf871) updates the version of `proto-loader` so it has `proto-loader-gen-types` tool, and adds a script that runs this tool to generate .ts types.
   All other brand-new .ts files in the commit are generated by this tool.
2. [Add types and typed GRPC service to all Services](https://github.com/spacemeshos/smapp/pull/809/commits/d6b8d3426bcd8716ea1e3a196872446278c122bf) refactors `NetServiceFactory` and all Services using new types.

Please, pay extra attention on `NetServiceFactory` generics and `callService` method.
Btw, if you have an idea of what is wrong here: https://github.com/spacemeshos/smapp/pull/809/commits/d6b8d3426bcd8716ea1e3a196872446278c122bf#diff-a3be8207b459dc6633aa14963b31223d163dc020b5b009946f69362dc9651466R16 I'll be happy if you help :)

### CODE REVIEW

**Comment by iamonuwa** [comment]
Trying to reproduce this PR locally, throws this error @brusherru
image

**Comment by brusherru** [comment]
@iamonuwa hmm, I can't reproduce the bug.
Could you provide more details?
- OS, clean start or you already have a created wallet, etc
- Steps to reproduce the bug (click here, open that, ...)

P.S.
It seems that this error should be thrown right on startup (Auth screen), but I've tried to run a clean start and second session and did not see this error in any case 🤔

**Comment by brusherru** [comment]
Anyway, please look at the code.
Maybe you have an idea how to simplify generics / provide a better developer experience (E.G. I don't like that as the first argument of `callService` I use the GRPC method name instead of the method itself. So it is quite complex to jump to the type definitions. But I don't have an idea how to solve this issue without moving back checks for null in every method.

**Review by iamonuwa — COMMENTED** [review]
LGTM!

**Comment by iamonuwa** [comment]
> @iamonuwa hmm, I can't reproduce the bug.
> Could you provide more details?
> 
> * OS, clean start or you already have a created wallet, etc
> * Steps to reproduce the bug (click here, open that, ...)
> 
> P.S.
> It seems that this error should be thrown right on startup (Auth screen), but I've tried to run a clean start and second session and did not see this error in any case 🤔

Now, it works fine.

**Comment by brusherru** [comment]
I successfully rebased https://github.com/spacemeshos/smapp/pull/810 on top of this PR to fix some of the bugs.
So this one can be finally merged 🙌 
@avive please, approve / request changes. Or ask someone else to review the code 🙏

**Comment by avive** [comment]
> I successfully rebased #810 on top of this PR to fix some of the bugs.
> So this one can be finally merged 🙌
> @avive please, approve / request changes. Or ask someone else to review the code 🙏

It is a bit hard to review the experience w/o knowing what should be expected to work and what should not yet. Maybe you can provide a quick list of features which are supposed to work in this build and features which are NYI?

**Review by avive — APPROVED** [review]
LGTM

**Comment by brusherru** [comment]
> Maybe you can provide a quick list of features which are supposed to work in this build and features which are NYI?

This PR doesn't implement any feature, only adds typings for GRPC API and use it within Services.
So in this PR should work anything that are expected on Smapp 0.2 without: gpu-post, wallet mode, tx and rewards API. So other things should work: network, status updating, creating/unlocking wallet, etc :)

**Pull request merged**
