### PR TITLE
Fix smesher screen issues + small fixes

### LINKED ISSUE #1066: Switching Wallets kicks off the POS data/Node sync
### Environment

* Smapp version: 0.2.9 | [develop] from [feature/handle-PoS-status]
* Node version: 45e5b646f83c3f5a54d13091bd9306f146cd9ede | devnet997
* OS: macOS Ventura Version 13.0.1

### Describe the bug

"Render error in kC component:Cannot read properties of undefined (reading 'numUnits')." after switching the Wallets

### Steps to reproduce

1. Create POS (synced node)
2. Log out
3. Log in to another Wallet
4. Try to reset up the POS data

### Expected behavior

The User should be able to use multiple Wallets with no issue

### Actual behavior

part 1

https://user-images.githubusercontent.com/89876259/209706017-ffc3b2e2-1292-42a3-8400-49bf449491f0.mov

part 2

https://user-images.githubusercontent.com/89876259/209707790-75ba56e2-d8fc-4b1e-8a08-6d33813ce732.mov

### Logs

[app-log.0.2.9.txt](https://github.com/spacemeshos/smapp/files/10310019/app-log.0.2.9.txt)
[app-log.0.2.9.old.txt](https://github.com/spacemeshos/smapp/files/10310020/app-log.0.2.9.old.txt)
[spacemesh-log-55dc4325e8d7f8f9824a47d646599420a2cf4516.txt](https://github.com/spacemeshos/smapp/files/10310025/spacemesh-log-55dc4325e8d7f8f9824a47d646599420a2cf4516.txt)

### How to fix 

N/A

### LINKED ISSUE #1072: After switching the network Smapp can not start Node properly
### Environment

* Smapp version: 0.2.10
* Node version: v0.2.20-beta.0
* OS: macOS BigSur 11.6

### Describe the bug
After switching the network in Smapp, it can not run he node properly (most likely it uses the same genesis id in arguments), moreover it can not start properly after clicking on "Restart node" button.
Restarting Smapp solves the problem.

### Steps to reproduce
1. Open Smapp
2. Unlock the wallet with local mode
3. Switch the network (to another working one)

### Expected behavior
Node restarted automatically and connected to the selected network.

### Actual behavior
Smapp restarts the Node with the same node-data directory argument.
As a consequence Node panics and Smapp can not restart the Node.
Clicking on "Restart Node" button does not solve the problem.
However, restarting Smapp is a workaround.

### LINKED ISSUE #1074: Smapp not showing updates from the node
### Environment

* Smapp version: 0.2.10
* Node version: v0.2.20-beta.0
* OS: every OS probably (?) macOS Ventura Version 13.0.1 + Windows 10 Home /11

### Describe the bug

The Smapp is getting frozen and not showing the following updates: 

- Epoch details on the Smeshing screen
- Layers details on the Network screen
- Rewards balance - the total values on the Smeshing and Wallet screen
- +other to be added if noticed

### Steps to reproduce

1.  Have Smapp open and synced 
2.  Set up POS creation
3.  Wait for some time  - at least until the next epoch 
4. +until rewards start to show up to check the SMH balance

### Expected behavior

All the details should be updated in real-time, or i.e., once per epoch. 

### Actual behavior

Only App restart / re-login makes Smapp to update those details. 

image (1)
image

### Logs

[spacemesh-log-16de29a9bf75f60233a482ec4c0a6202e4d8c5be.txt](https://github.com/spacemeshos/smapp/files/10355964/spacemesh-log-16de29a9bf75f60233a482ec4c0a6202e4d8c5be.txt)

app-log, stopped at 9:25 PM, app still running for hours after that.

```
[2023-01-05 14:05:33.284] [info]  SmesherService, in grpc PostDataCreationProgressStream, output: {"state":4,"numLabelsWritten":4096} 
[2023-01-05 14:05:34.286] [info]  SmesherService, in grpc PostDataCreationProgressStream, output: {"state":4,"numLabelsWritten":4096} 
[2023-01-05 14:05:35.281] [info]  SmesherService, in grpc PostDataCreationProgressStream, output: {"state":4,"numLabelsWritten":4096} 
[2023-01-05 14:05:35.887] [info]  NodeManager, in stop node, output: "kill SIGTERM" 
[2023-01-05 14:05:35.887] [info]  NodeManager, in Spawn process, output: "Wait process to finish isFinished: true, timeout: 20000, interval: 1000" 
[2023-01-05 14:05:35.889] [info]  NodeManager, in stop node, output: "node process is null" 
[2023-01-05 14:05:35.906] [error] rx, in spawnManagers$ > Can not spawn new managers, error: {} ; args: "16de29a9bf75f60233a482ec4c0a6202e4d8c5be"
[2023-01-05 14:05:36.373] [error] NodeService, in grpc StatusStream, error: {"code":13,"details":"Received RST_STREAM with code 2 triggered by internal client error: read ECONNRESET","metadata":{"internalRepr":{},"options":{}}} 
[2023-01-05 14:05:36.375] [error] NodeService, in grpc ErrorStream, error: {"code":13,"details":"Received RST_STREAM with code 2 triggered by internal client error: read ECONNRESET","metadata":{"internalRepr":{},"options":{}}} 
[2023-01-05 14:05:36.376] [error] SmesherService, in grpc PostDataCreationProgressStream, error: {"code":13,"details":"Received RST_STREAM with code 2 triggered by internal client error: read ECONNRESET","metadata":{"internalRepr":{},"options":{}}} 
[2023-01-05 14:05:36.377] [error] MeshService, in grpc call MeshService.AccountMeshDataQuery, error: {"code":13,"details":"Received RST_STREAM with code 2 triggered by internal client error: read ECONNRESET","metadata":{"internalRepr":{},"options":{}}} 
[2023-01-05 14:05:36.377] [error] MeshService, in grpc call MeshService.AccountMeshDataQuery, error: {"code":13,"details":"Received RST_STREAM with code 2 triggered by internal client error: read ECONNRESET","metadata":{"internalRepr":{},"options":{}}} 
[2023-01-05 14:05:36.378] [error] MeshService, in grpc call MeshService.AccountMeshDataQuery, error: {"code":13,"details":"Received RST_STREAM with code 2 triggered by internal client error: read ECONNRESET","metadata":{"internalRepr":{},"options":{}}} 
[2023-01-05 14:05:36.379] [info]  NodeService, in grpc StatusStream ended, output: null 
[2023-01-05 14:05:36.379] [info]  NodeService, in grpc StatusStream restarting, output: "Retries left: 5" 
[2023-01-05 14:05:36.380] [info]  NodeService, in grpc ErrorStream ended, output: null 
[2023-01-05 14:05:36.380] [info]  NodeService, in grpc ErrorStream restarting, output: "Retries left: 5" 
[2023-01-05 18:21:52.762] [info]  NodeManager, in startNode, output: "spawning node" ; args: ["C:\\Users\\sm\\AppData\\Local\\Programs\\Spacemesh\\node\\go-spacemesh.exe","--config","C:\\Users\\sm\\AppData\\Roaming\\Spacemesh\\node-config.json","-d","C:\\Users\\sm\\AppData\\Roaming\\Spacemesh\\node-data\\16de29a9"]
[2023-01-05 18:21:52.775] [error] NodeService, in grpc call NodeService.Echo, error: {"code":14,"details":"No connection established","metadata":{"internalRepr":{},"options":{}}} 
[2023-01-05 18:21:53.279] [error] NodeService, in grpc call NodeService.Echo, error: {"code":14,"details":"No connection established","metadata":{"internalRepr":{},"options":{}}} 
[2023-01-05 18:22:01.448] [error] SmesherService, in grpc call SmesherService.StartSmeshing, error: {"code":13,"details":"failed to start smeshing: already started","metadata":{"internalRepr":{},"options":{}}} 
[2023-01-05 18:22:01.449] [error] handleSmesherIpc, in NodeManager.startSmeshing failed, error: {"code":13,"details":"failed to start smeshing: already started","metadata":{"internalRepr":{},"options":{}}} 
[2023-01-05 21:25:48.440] [error] NodeService, in grpc StatusStream, error: {"code":14,"details":"Connection dropped","metadata":{"internalRepr":{},"options":{}}} 
[2023-01-05 21:25:48.441] [info]  NodeService, in grpc StatusStream ended, output: null 
[2023-01-05 21:25:48.442] [info]  NodeService, in grpc StatusStream restarting, output: "Retries left: 5" 
[2023-01-05 21:25:48.444] [error] NodeService, in grpc ErrorStream, error: {"code":1,"details":"Call cancelled","metadata":{"internalRepr":{},"options":{}}} 
[2023-01-05 21:25:48.445] [info]  NodeService, in grpc ErrorStream ended, output: null 
[2023-01-05 21:25:48.446] [info]  NodeService, in grpc ErrorStream restarting, output: "Retries left: 5" 
```

### How to fix 
/
Probably the issue will need to be split (?)

### LINKED ISSUE #1075: Closing Smapp - "run in background?" pop-up to be checked
### Environment

- Smapp version: 0.2.10
- Node version: v0.2.20-beta.0
- OS: every OS probably (?) 

### Describe the bug

When the node runs, the "X" button (close app) should trigger a pop-up window asking the user whether to close the app or keep it running In the background. This notification window was not shown even though the node was supposedly running. 

### Steps to reproduce

1. have a local node running
2. try to close the app

### Expected behavior

Screenshot 2023-01-04 at 17 33 22

### Actual behavior

The app was closed with no notification. 

### Logs

`[2023-01-04 16:46:20.268] [error] NodeService, in grpc call NodeService.Echo, error: {"code":14,"details":"No connection established","metadata":{"internalRepr":{},"options":{}}} `

### How to fix 

> maybe was some gap between node disconnection

### PR DESCRIPTION
**Pull request by brusherru**
It closes #1066 
And, I believe, the rest of the issues with Smesher screen :D
Also, I've returned the possibility to set up PoS without waiting to sync the node, and all works well.

Besides this, I:
- allowed to send one more (next to pending) spawn tx after some delay (3 layers). Just in case some transaction gets stuck, the User will be able to send another tx.
- fixed displaying of PublicKey in the transaction log
- fixed displaying of Rewards (now the sums are correct, @lrettig)
- fixed #1072 (switching the network)
- fixed retrieving of rewards for smesher (and made a temporary kludge due to https://github.com/spacemeshos/go-spacemesh/issues/3935)
- [commit](https://github.com/spacemeshos/smapp/pull/1076/commits/2257f6698cd9d3f25bf568958f85e79a0eb94731) should fix #1074 — the reason of it was that on closed streams `activateNodeStatusStream` and `activateNodeErrorStream` they runs this method again, but since it keeps the reference to the closed stream — it does nothing. So now I fixed it

A bunch of fundamental problems were solved within [refactoring commit](https://github.com/spacemeshos/smapp/pull/1076/commits/cd08c1d66b7f5d4a830eb352219a77637c90a05f), so I want to provide some details:
1. Instead of storing manager class instances in RxJs subject now we're storing the only reference to the single collection of Managers. Afterward, we're not re-creating new instances all the time, but updating dependencies (`mainWindow` and `genesisId`).
2. Some logic over updating `mainWindow` and sub/unsub was moved into the `AbstractManager` class
3. It fixes #1072, because previously `NodeManager` spawns a Node with the new node-config (points to a new network), but using the old node-data dir because it contains the same `genesisId` created in a constructor.
4. Probably it also fixes #1075. Since Smapp does not show this dialog it means, that Smapp thinks that the Node process is not running. It may happen in case we re-spawned NodeManager and the reference to the process has been lost. However, now we have a single instance of each manager per application session.

### CODE REVIEW

**Review by monikasmolarek — CHANGES_REQUESTED** [review]
Steps I performed on Windows - having only 1 Wallet all the time, no switching: 

1. I wanted to test editing POS, and I received "SMESHER STOP SMESHING
2. I restarted SMAPP, but then got "POS INITIALIZATION FAILED. TRY TO DELETE IT AND RE-INITIALIZE."
3. So I reinitialized and got "Cannot read properties of undefined reading numUnits)"





App-log: 
```
[2023-01-06 20:07:25.563] [info]  SmesherService, in grpc PostDataCreationProgressStream, output: {"state":4,"numLabelsWritten":4096} 
[2023-01-06 20:07:26.441] [info]  NodeManager, in stop node, output: "kill SIGTERM" 
[2023-01-06 20:07:26.443] [info]  NodeManager, in Spawn process, output: "Wait process to finish isFinished: true, timeout: 20000, interval: 1000" 
[2023-01-06 20:07:26.443] [info]  NodeManager, in stop node, output: "node process is null" 
[2023-01-06 20:07:26.445] [error] SmesherService, in grpc PostDataCreationProgressStream, error: {"code":1,"details":"Cancelled on client","metadata":{"internalRepr":{},"options":{}}} 
[2023-01-06 20:07:34.824] [info]  Checking for update
[2023-01-06 20:07:34.888] [debug] update-error NetError: Error: net::ERR_NAME_NOT_RESOLVED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:101:7169)
    at SimpleURLLoaderWrapper.emit (node:events:527:28)
    at SimpleURLLoaderWrapper.emit (node:domain:475:12)
[2023-01-06 20:07:35.582] [info]  NodeManager, in startNode, output: "spawning node" ; args: ["C:\\Users\\sm\\AppData\\Local\\Programs\\Spacemesh\\node\\go-spacemesh.exe","--config","C:\\Users\\sm\\AppData\\Roaming\\Spacemesh\\node-config.json","-d","C:\\Users\\sm\\AppData\\Roaming\\Spacemesh\\node-data\\16de29a9"]
[2023-01-06 20:07:35.618] [error] NodeService, in grpc call NodeService.Echo, error: {"code":14,"details":"No connection established","metadata":{"internalRepr":{},"options":{}}} 
[2023-01-06 20:07:36.120] [error] NodeService, in grpc call NodeService.Echo, error: {"code":14,"details":"No connection established","metadata":{"internalRepr":{},"options":{}}} 
[2023-01-06 20:08:07.996] [info]  SmesherService, in checkDiskSpace, output: 147407290368 ; args: {"dataDir":"C:\\Users\\sm\\Desktop\\POS2"}
[2023-01-06 20:08:22.873] [info]  SmesherService, in checkDiskSpace, output: 147407220736 ; args: {"dataDir":"C:\\Users\\sm\\Desktop\\POS"}
[2023-01-06 20:08:31.402] [info]  NodeManager, in restartNode, output: "restarting node..." 
[2023-01-06 20:08:31.403] [info]  NodeManager, in stop node, output: "kill SIGTERM" 
[2023-01-06 20:08:31.404] [info]  NodeManager, in Spawn process, output: "Wait process to finish isFinished: true, timeout: 20000, interval: 1000" 
[2023-01-06 20:08:31.404] [info]  NodeManager, in stop node, output: "node process is null" 
[2023-01-06 20:08:31.411] [info]  NodeManager, in startNode, output: "spawning node" ; args: ["C:\\Users\\sm\\AppData\\Local\\Programs\\Spacemesh\\node\\go-spacemesh.exe","--config","C:\\Users\\sm\\AppData\\Roaming\\Spacemesh\\node-config.json","-d","C:\\Users\\sm\\AppData\\Roaming\\Spacemesh\\node-data\\16de29a9"]
[2023-01-06 20:08:31.834] [error] NodeService, in grpc StatusStream, error: {"code":13,"details":"Received RST_STREAM with code 2 triggered by internal client error: read ECONNRESET","metadata":{"internalRepr":{},"options":{}}} 
[2023-01-06 20:08:34.109] [error] NodeService, in grpc ErrorStream, error: {"code":13,"details":"Received RST_STREAM with code 2 triggered by internal client error: read ECONNRESET","metadata":{"internalRepr":{},"options":{}}} 
[2023-01-06 20:08:34.110] [error] MeshService, in grpc MeshService.AccountMeshDataStream, error: {"code":13,"details":"Received RST_STREAM with code 2 triggered by internal client error: read ECONNRESET","metadata":{"internalRepr":{},"options":{}}} ; args: "Retries left: 5"
[2023-01-06 20:08:34.112] [error] GlobalStateService, in grpc GlobalStateService.AccountDataStream, error: {"code":13,"details":"Received RST_STREAM with code 2 triggered by internal client error: read ECONNRESET","metadata":{"internalRepr":{},"options":{}}} ; args: "Retries left: 5"
[2023-01-06 20:08:34.112] [error] GlobalStateService, in grpc GlobalStateService.AccountDataStream, error: {"code":13,"details":"Received RST_STREAM with code 2 triggered by internal client error: read ECONNRESET","metadata":{"internalRepr":{},"options":{}}} ; args: "Retries left: 5"
[2023-01-06 20:08:34.113] [error] TransactionService, in grpc TransactionService.StreamResults, error: {"code":13,"details":"Received RST_STREAM with code 2 triggered by internal client error: read ECONNRESET","metadata":{"internalRepr":{},"options":{}}} ; args: "Retries left: 5"
[2023-01-06 20:08:34.114] [error] NodeService, in grpc call NodeService.Echo, error: {"code":13,"details":"Received RST_STREAM with code 2 triggered by internal client error: read ECONNRESET","metadata":{"internalRepr":{},"options":{}}} 
[2023-01-06 20:08:34.115] [info]  NodeService, in grpc StatusStream ended, output: null 
[2023-01-06 20:08:34.116] [info]  NodeService, in grpc StatusStream restarting, output: "Retries left: 5" 
[2023-01-06 20:08:34.118] [info]  NodeService, in grpc ErrorStream ended, output: null 
[2023-01-06 20:08:34.119] [info]  NodeService, in grpc ErrorStream restarting, output: "Retries left: 5" 
[2023-01-06 20:08:35.633] [info]  SmesherService, in grpc PostDataCreationProgressStream, output: {"state":1} 
[2023-01-06 20:08:36.633] [info]  SmesherService, in grpc PostDataCreationProgressStream, output: {"state":1} 
[2023-01-06 20:08:37.631] [info]  SmesherService, in grpc PostDataCreationProgressStream, output: {"state":1} 
[2023-01-06 20:08:38.636] [info]  SmesherService, in grpc PostDataCreationProgressStream, output: {"state":1} 
[2023-01-06 20:08:39.121] [error] MeshService, in grpc MeshService.AccountMeshDataStream restarting..., error: null 
[2023-01-06 20:08:39.122] [error] GlobalStateService, in grpc GlobalStateService.AccountDataStream restarting..., error: null 
[2023-01-06 20:08:39.123] [error] GlobalStateService, in grpc GlobalStateService.AccountDataStream restarting..., error: null 
[2023-01-06 20:08:39.124] [error] TransactionService, in grpc TransactionService.StreamResults restarting..., error: null 
[2023-01-06 20:08:39.631] [info]  SmesherService, in grpc PostDataCreationProgressStream, output: {"state":1} 
[2023-01-06 20:08:40.632] [info]  SmesherService, in grpc PostDataCreationProgressStream, output: {"state":1} 
[2023-01-06 20:08:41.631] [info]  SmesherService, in grpc PostDataCreationProgressStream, output: {"state":1} 
[2023-01-06 20:08:42.672] [info]  SmesherService, in grpc PostDataCreationProgressStream, output: {"state":1} 
[2023-01-06 20:08:42.766] [error] SmesherService, in grpc PostDataCreationProgressStream, error: {"code":1,"details":"Cancelled on client","metadata":{"internalRepr":{},"options":{}}} 
[2023-01-06 20:08:43.691] [info]  NodeManager, in stop node, output: "kill SIGTERM" 
[2023-01-06 20:08:43.692] [info]  NodeManager, in Spawn process, output: "Wait process to finish isFinished: true, timeout: 20000, interval: 1000" 
[2023-01-06 20:08:43.693] [info]  NodeManager, in stop node, output: "node process is null" 
[2023-01-06 20:08:43.710] [error] rx, in spawnManagers$ > Can not spawn new managers, error: {} ; args: "16de29a9bf75f60233a482ec4c0a6202e4d8c5be"
[2023-01-06 20:08:43.766] [error] NodeService, in grpc StatusStream, error: {"code":13,"details":"Received RST_STREAM with code 2 triggered by internal client error: read ECONNRESET","metadata":{"internalRepr":{},"options":{}}} 
[2023-01-06 20:08:43.767] [error] NodeService, in grpc ErrorStream, error: {"code":13,"details":"Received RST_STREAM with code 2 triggered by internal client error: read ECONNRESET","metadata":{"internalRepr":{},"options":{}}} 
[2023-01-06 20:08:43.768] [error] MeshService, in grpc call MeshService.AccountMeshDataQuery, error: {"code":13,"details":"Received RST_STREAM with code 2 triggered by internal client error: read ECONNRESET","metadata":{"internalRepr":{},"options":{}}} 
[2023-01-06 20:08:43.768] [error] MeshService, in grpc call MeshService.AccountMeshDataQuery, error: {"code":13,"details":"Received RST_STREAM with code 2 triggered by internal client error: read ECONNRESET","metadata":{"internalRepr":{},"options":{}}} 
[2023-01-06 20:08:43.770] [error] MeshService, in grpc call MeshService.AccountMeshDataQuery, error: {"code":13,"details":"Received RST_STREAM with code 2 triggered by internal client error: read ECONNRESET","metadata":{"internalRepr":{},"options":{}}} 
[2023-01-06 20:08:43.771] [error] SmesherService, in grpc PostDataCreationProgressStream, error: {"code":13,"details":"Received RST_STREAM with code 2 triggered by internal client error: read ECONNRESET","metadata":{"internalRepr":{},"options":{}}} 
[2023-01-06 20:08:43.772] [error] SmesherService, in grpc call SmesherService.PostSetupComputeProviders, error: {"code":13,"details":"Received RST_STREAM with code 2 triggered by internal client error: read ECONNRESET","metadata":{"internalRepr":{},"options":{}}} 
[2023-01-06 20:08:43.772] [info]  NodeService, in grpc StatusStream ended, output: null 
[2023-01-06 20:08:43.773] [info]  NodeService, in grpc StatusStream restarting, output: "Retries left: 5" 
[2023-01-06 20:08:43.773] [info]  NodeService, in grpc ErrorStream ended, output: null 
[2023-01-06 20:08:43.773] [info]  NodeService, in grpc ErrorStream restarting, output: "Retries left: 5" 
[2023-01-06 20:08:43.778] [error] SmesherService, in grpc call SmesherService.PostConfig, error: {"code":14,"details":"No connection established","metadata":{"internalRepr":{},"options":{}}} 
[2023-01-06 20:08:43.779] [error] SmesherService, in grpc call SmesherService.SmesherID, error: {"code":14,"details":"No connection established","metadata":{"internalRepr":{},"options":{}}} 
```

**Comment by monikasmolarek** [comment]
I cannot check whether "_Switching Wallets kicks off the POS data/Node sync"_, because this is what happens when I want to switch the Wallets (both with local node mode): 


https://user-images.githubusercontent.com/89876259/211098928-069e17db-8254-4048-9ddb-0340924edfe8.mov

**Comment by brusherru** [comment]
@monikasmolarek it would be very helpful to see the corresponding part of the Node log (spacemesh-logs-16...txt).
Seems like Node gets restarted for some reason. Could you check out the corresponding parts (by timestamp) of the log for both reports?
I am a bit confused since I can't reproduce anything similar both on Mac and Win 11 (running in parallels) 🙈

**Comment by monikasmolarek** [comment]
Windows logs:
[spacemesh-log-16de29a9bf75f60233a482ec4c0a6202e4d8c5be.txt](https://github.com/spacemeshos/smapp/files/10365891/spacemesh-log-16de29a9bf75f60233a482ec4c0a6202e4d8c5be.txt)

**Comment by maparr** [comment]
Steps to reproduce:
1. Attach folder or already attached
2. Delete data ( modify ), node is not synced, for example, progress on 119
3. Attach new folder or modify PoS and select the new folder 

As result the Delete or Modify PoS already not possible till restart

Screenshot 2023-01-07 at 14 11 56

**Comment by brusherru** [comment]
Due to the latest updates in the PR I've updated the description in the first comment.
Please check it out 🙏 
cc: @monikasmolarek @maparr

**Review by maparr — DISMISSED** [review]

**Comment by brusherru** [comment]
Added one more commit, which fixes #1074.
The problem was that Node disconnects the client [after some time](https://github.com/spacemeshos/go-spacemesh/blob/develop/api/grpcserver/grpc.go#L85), then the stream became closed and it tries to restart the stream. However, since we're just checking for reference — we never restart streams. Now it is fixed.

**Review by monikasmolarek — DISMISSED** [review]
Good enough 
POS seems to be working correctly (I didn’t start getting rewards, but manipulating with POS setup and switching wallets works well). 
Other details OK. Except for the Node-related updates - Current Layers. and epochs are still not displayed / refreshed correctly. 
Screenshot 2023-01-12 at 19 34 14
Screenshot 2023-01-12 at 20 27 04

**Comment by brusherru** [comment]
@monikasmolarek now it is fixed ;)

**Review by monikasmolarek — APPROVED** [review]
edited: Still having performance issues- app freezes and CPU usage is in general constantly high

**Pull request merged**
