### PR TITLE
Show the disabled button "Wait for sync" on the wallet screen

### PR DESCRIPTION
**Pull request by brusherru**
To avoid confusing when it shows "SPAWN" button while the node is still syncing...

image

### CODE REVIEW

**Comment by Stizerg** [comment]
What about that message at the top?
"The account is not spawned yet"

**Comment by brusherru** [comment]
@Stizerg done!

image

**Review by monikasmolarek — COMMENTED** [review]
@brusherru do you think it would be ok to address also this Smesher screen within this PR or should I create a separate issue for it? 


https://github.com/spacemeshos/smapp/assets/89876259/850c8fbe-52fa-4527-8f73-0b7bccce2891

**Comment by brusherru** [comment]
@monikasmolarek let's make it a separate one and describe details

**Review by pigmej — APPROVED** [review]

**Pull request merged**
