### PR TITLE
Add upload to R2 to pr-build workflow

### PR DESCRIPTION
**Pull request by andres-spacemesh**

### CODE REVIEW

**Comment by brusherru** [comment]
Shouldn't it replace uploading to GCP?
Btw, it is failing...

**Comment by brusherru** [comment]
@andres-spacemesh shouldn't we remove these lines?
https://github.com/spacemeshos/smapp/pull/1763/files#diff-404033996c34f9971e0c112d8538b9063618fc85059a44df7d4db448974888caR228-R267

**Comment by andres-spacemesh** [comment]
Uploading on both CF and GCP for now. Eventually it'll be removed

**Review by brusherru — APPROVED** [review]
LGTM

**Pull request merged**
