### PR TITLE
Increased number of attempts before showing red banner

### PR DESCRIPTION
**Pull request by IlyaVi**

### CODE REVIEW

**Comment by IlyaVi** [comment]
bug: red "no connection" banner appear too soon before node finished loading up and starts to respond

**Comment by yaelmhoffman** [comment]
Do we have a particular scenario where this happens? Like, after the app is closed and reopened?

**Comment by IlyaVi** [comment]
it used to happen especially after app was synced, than closed for some time and opened again to trigger node cache warmup. Or on fresh install with bad internet connection

**Comment by yaelmhoffman** [comment]
Build: v0.0.6
OS: Windows 10 Home & Pro
Fix confirmed.

**Pull request merged**
