### PR TITLE
Build Smapp for arm64 (macOS, linux)

### PR DESCRIPTION
**Pull request by brusherru**
No issue.

Now it produces 5 build artifacts:
- win [x64]
- mac [x64, arm64]
- linux [x64, arm64]

### CODE REVIEW

**Comment by brusherru** [comment]
I've rebased these changes on `develop` and gotten rid of updating `use-version`.
As a consequence current build of this PR will fail. To merge it we should add one more commit which will bump `use-version` to the newer go-spacemesh release, which supports arm64 builds.

Meanwhile, for testing purposes, I've created a separate branch and PR: https://github.com/spacemeshos/smapp/pull/1131

**Comment by brusherru** [comment]
Test builds on top of these changes: https://github.com/spacemeshos/smapp/pull/1131#issuecomment-1423450504

**Review by pigmej — DISMISSED** [review]

**Comment by brusherru** [comment]
Ok, had a small typo in the release workflow.

Now it is fixed, and all works:
- PR workflow: https://github.com/spacemeshos/smapp/pull/1131#issuecomment-1424494808
- Release workflow result (signed):
   - Windows: https://storage.googleapis.com/smapp/v0.2.11-test.arm64/Spacemesh%20Setup%200.2.11-test.arm64.exe
   - macOS: https://storage.googleapis.com/smapp/v0.2.11-test.arm64/Spacemesh-0.2.11-test.arm64.dmg
   - macOS ARM64: https://storage.googleapis.com/smapp/v0.2.11-test.arm64/Spacemesh-0.2.11-test.arm64-arm64.dmg
   - Linux: https://storage.googleapis.com/smapp/v0.2.11-test.arm64/spacemesh_app_0.2.11-test.arm64_amd64.deb
   - Linux ARM64: https://storage.googleapis.com/smapp/v0.2.11-test.arm64/spacemesh_app_0.2.11-test.arm64_arm64.deb
   
All these builds have go-spacemesh v0.0.0-test-arm64 under the hood.
So it won't work on current devnets. But you can still try to run it :)

If no complains / change requests — then we're waiting for the newer go-spacemesh release (with arm64 artifacts), then bumping `use-version` in this PR (checks will become green) and merging :)

**Review by maparr — DISMISSED** [review]

**Comment by brusherru** [comment]
Rebased it on top of `develop` and bumped `use-version` to `v0.2.22-beta.0`.

**Pull request merged**
